cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.11.2
#  - 2.10.4
#  - 2.9.3
jdk:
  - oraclejdk8
#  - openjdk7

before_install:
#  - sudo apt-get install libimage-exiftool-perl
  - sudo apt-get update
  - sudo apt-get install wget
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.08.tar.gz
  - tar -xzf Image-ExifTool-10.08.tar.gz
  - cd Image-ExifTool-10.08
  - perl Makefile.PL
  - make
  - sudo make install
  - cd ..
  - exiftool -ver
#-Dexiftool.path=$HOME/Image-ExifTool-9.27/exiftool
